const finesData = [
    { "name": "An", "fine": 1720.0 },
    { "name": "Kiệt", "fine": 1580.0 },
    { "name": "A. Thuận", "fine": 1480.0 },
    { "name": "Quỳnh", "fine": 1355.0 },
    { "name": "Linh AI", "fine": 1350.0 },
    { "name": "Tùng", "fine": 960.0 },
    { "name": "A. Phúc D", "fine": 695.0 },
    { "name": "Ylu", "fine": 645.0 },
    { "name": "Anh Loc", "fine": 570.0 },
    { "name": "Linh Đào", "fine": 560.0 },
    { "name": "A. Orj", "fine": 539.0 },
    { "name": "Hưng", "fine": 520.0 },
    { "name": "Tuấn", "fine": 385.0 },
    { "name": "Duy", "fine": 370.0 },
    { "name": "Tâm", "fine": 340.0 },
    { "name": "Hùng", "fine": 315.0 },
    { "name": "Tú", "fine": 265.0 },
    { "name": "A. Phúc T", "fine": 200.0 },
    { "name": "Ngọc", "fine": 170.0 },
    { "name": "Huy", "fine": 160.0 },
    { "name": "Anh Thuấn", "fine": 100.0 },
    { "name": "Hải", "fine": 70.0 },
    { "name": "Chi Lam", "fine": 60.0 },
    { "name": "Phúc Mai", "fine": 60.0 },
    { "name": "Vân", "fine": 50.0 },
    { "name": "Hiền", "fine": 40.0 },
    { "name": "Lâm", "fine": 40.0 },
    { "name": "A Thủy", "fine": 40.0 },
    { "name": "A. Toản", "fine": 10.0 },
    { "name": "Nga", "fine": 10.0 },
    { "name": "Chị Cindy", "fine": 10.0 }
];
